// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"
	request "movie-rating-service/internal/application/models/request"

	mock "github.com/stretchr/testify/mock"

	response "movie-rating-service/internal/application/models/response"
)

// MovieService is an autogenerated mock type for the MovieService type
type MovieService struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, req
func (_m *MovieService) Create(ctx context.Context, req request.CreateMovie) (*response.CreateMovie, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *response.CreateMovie
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, request.CreateMovie) (*response.CreateMovie, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, request.CreateMovie) *response.CreateMovie); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*response.CreateMovie)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, request.CreateMovie) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Get provides a mock function with given fields: ctx, req
func (_m *MovieService) Get(ctx context.Context, req request.GetMovie) (*response.GetMovie, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *response.GetMovie
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, request.GetMovie) (*response.GetMovie, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, request.GetMovie) *response.GetMovie); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*response.GetMovie)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, request.GetMovie) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMovieService creates a new instance of MovieService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMovieService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MovieService {
	mock := &MovieService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
