// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "movie-rating-service/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// MovieRepository is an autogenerated mock type for the MovieRepository type
type MovieRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, movie
func (_m *MovieRepository) Create(ctx context.Context, movie domain.Movie) (*domain.Movie, error) {
	ret := _m.Called(ctx, movie)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *domain.Movie
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Movie) (*domain.Movie, error)); ok {
		return rf(ctx, movie)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.Movie) *domain.Movie); ok {
		r0 = rf(ctx, movie)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Movie)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.Movie) error); ok {
		r1 = rf(ctx, movie)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Get provides a mock function with given fields: ctx, id
func (_m *MovieRepository) Get(ctx context.Context, id uint) (*domain.Movie, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *domain.Movie
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (*domain.Movie, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) *domain.Movie); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Movie)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields: ctx
func (_m *MovieRepository) List(ctx context.Context) ([]domain.Movie, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []domain.Movie
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]domain.Movie, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []domain.Movie); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Movie)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateRating provides a mock function with given fields: ctx, movieID, score
func (_m *MovieRepository) UpdateRating(ctx context.Context, movieID uint, score float64) error {
	ret := _m.Called(ctx, movieID, score)

	if len(ret) == 0 {
		panic("no return value specified for UpdateRating")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, float64) error); ok {
		r0 = rf(ctx, movieID, score)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMovieRepository creates a new instance of MovieRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMovieRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MovieRepository {
	mock := &MovieRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
