// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "movie-rating-service/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// RatingRepository is an autogenerated mock type for the RatingRepository type
type RatingRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, rating
func (_m *RatingRepository) Create(ctx context.Context, rating domain.Rating) (*domain.Rating, error) {
	ret := _m.Called(ctx, rating)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *domain.Rating
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Rating) (*domain.Rating, error)); ok {
		return rf(ctx, rating)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.Rating) *domain.Rating); ok {
		r0 = rf(ctx, rating)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Rating)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.Rating) error); ok {
		r1 = rf(ctx, rating)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByUserID provides a mock function with given fields: ctx, userID
func (_m *RatingRepository) GetByUserID(ctx context.Context, userID uint) ([]domain.Rating, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetByUserID")
	}

	var r0 []domain.Rating
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) ([]domain.Rating, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) []domain.Rating); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Rating)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewRatingRepository creates a new instance of RatingRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRatingRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *RatingRepository {
	mock := &RatingRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
