// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Seeder is an autogenerated mock type for the Seeder type
type Seeder struct {
	mock.Mock
}

// Seed provides a mock function with no fields
func (_m *Seeder) Seed() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Seed")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewSeeder creates a new instance of Seeder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSeeder(t interface {
	mock.TestingT
	Cleanup(func())
}) *Seeder {
	mock := &Seeder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
