run:
  timeout: 3m
  tests: true


linters:
  enable:
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - structcheck
    - deadcode
    - typecheck
    - gofmt
    - gocritic
    - dupl


issues:
  max-issues-per-linter: 0
  max-same-issues: 0


output:
  format: colored-line-number
  sort-results: true
