run:
  timeout: 3m
  tests: true
  skip-dirs:
    - vendor
    - docs
  skip-files:
    - ".*.gen.go"

linters:
  enable:
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - structcheck
    - deadcode
    - typecheck
    - gofmt
    - gocritic
    - dupl

linters-settings:
  gofmt:
    simplify: true

  goimports:
    local-prefixes: movie-rating-service

  errcheck:
    check-type-assertions: true
    check-blank: true

  depguard:
    list-type: blacklist
    packages:
      - github.com/sirupsen/logrus
      - github.com/pkg/errors
    packages-with-error-message:
      github.com/sirupsen/logrus: "Use slog instead of logrus"
      github.com/pkg/errors: "Use native Go 1.20+ errors package"

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude:
    - "context\\.TODO"
    - "Error return value of .+ is not checked"

output:
  format: colored-line-number
  sort-results: true