apiVersion: v1
kind: Service
metadata:
  name: movie-rating-service-service
spec:
  selector:
    app: movie-rating-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-rating-service-deployment
  labels:
    app: movie-rating-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movie-rating-service
  template:
    metadata:
      labels:
        app: movie-rating-service
    spec:
      containers:
        - name: movie-rating-service
          image: movie-rating-service:latest
          ports:
            - containerPort: 8080
          env:
            - name: ENVIRONMENT
              value: "dev"
            - name: DEBUG_MODE
              value: "false"
            - name: PORT
              value: "8080"
            - name: JWT_SECRET
              value: "secret"
            - name: DB_USER
              value: "thermondo_user"
            - name: DB_PASSWORD
              value: "thermondo_pass"
            - name: DB_HOST
              value: "postgresdb"
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: "thermondo"
            - name: DB_SSLMODE
              value: "disable"
