apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-rating-service-deployment
  labels:
    app: movie-rating-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movie-rating-service
  template:
    metadata:
      labels:
        app: movie-rating-service
    spec:
      containers:
        - name: movie-rating-service
          image: movie-rating-service:latest
          ports:
            - containerPort: 8080
          env:
            - name: ENVIRONMENT
              value: "dev"
            - name: DEBUG_MODE
              value: "false"
            - name: DATABASE
              value: "/app/test.db"
            - name: PORT
              value: "8080"
