apiVersion: v1
kind: Service
metadata:
  name: movie-rating-service-service
spec:
  selector:
    app: movie-rating-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
